= IDN Catalogue Data

This repository contains the data of the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)]'s catalogue.

The IDN is producing a catalogue of Australian datasets with varying levels of indigenous relevance to demonstrate several aspects of indigenous data governance, sovereignty and how to even rate the "indigenous-ness" of data in the first place.

This repository only contains the bare data files of the catalogue, not the catalogue's system code. The catalogue data is dataset metadata formulated according to the _IDN metadata profile_ of https://www.w3.org/TR/vocab-dcat/[DCAT] which is a data cataloguing standard. Individual metadata records are stored in the `data/` folder of this repository, named with each record's Persistent Identifier. The data files are both human- and machine-readable and the catalogue tool reads these files, joins them to background details (models, vocabularies etc) and presents them online in pleasent HTML (web pages) and (will) also give https://force11.org/info/the-fair-data-principles/[FAIR], https://www.gida-global.org/care[CARE] and https://localcontexts.org/labels/traditional-knowledge-labels/[TK Label] ratings/assessments of them, based on their medata and mappings that the IDN have created.

A simple listing of the assets in this repository are:

* `data/` folder
** contains all the metadata records for the catalogue
* `_background/` folder within `data/`
** contains further the ontologies used by the data, mainly for nice property labels
** `agents/` - the Agents database
** `resources/` - the IDN's demo catalogue Resources (metadata records)
** `vocabularies/` - all IDN vocabularies
** `_system_catalogue.ttl` - the metadata for the IDN system as a whole

NOTE: spatial data loaded into the IDN Knowledge Graph is not stored in this repository but in <https://github.com/idn-au/spatial-data-etl>


== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.


== Contacts

Initial technical development of this work is being undertaken by the following, for the Indigenous Data Network:

**Nicholas J. Car** +
*Data Architect* +
nick@kurrawong.net  

**Sandra Silcot** +
*Analyst* +
Indigenous Data Network +
