= IDN Catalogue Data

This repository contains part of the data of the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)]'s Knowledge Graph which is delivered online via the https://github.com/rdflib/prez/[Prez] system as a series of catalogues and reference datasets, such as spatial data collections and vocabularies.

The IDN Prez system is online at:

* **https://data.idnau.org**

== IDN Catalogues and Datasets

The IDN is producing multiple systems and datasets:

. https://data.idnau.org/pid/democat[**Demonstration Catalogue**] of Australian datasets
** with varying levels of indigenous relevance to demonstrate several aspects of indigenous data governance, sovereignty and how to even rate the "indigenous-ness" of data in the first place.
. https://data.idnau.org/pid/agentsdb[**Agents Database**]
** containing information about Agents - People and Organisations - that have some relation to indigenous data
. https://data.idnau.org/pid/umidcat[**University of Melbourne's Indigenous Data Catalogue**]
** this is currently (May, 2023) empty but will fill shortly
. https://data.idnau.org/v/vocab[**Register of vocabularies**]
** multiple vocabularies, all assembled and some created, by the IDN that support modelling indigenous data
. https://data.idnau.org/s/datasets[**Indigenous spatial reference data**]
** indigenous language, land use, treaty and other areas
** all from other sources, attributed in the data

Additionally, the IDN will support a catalogue of https://www.anu.edu.au[ANU]'s indigenous data underdevelopment by ANU's https://anufirstnations.com.au/[First National Portfolio] that's not online yet.

This repository contains only some of those system's data, see next.

== This repository's content
This repository contains:

* Demonstration Catalogue items' metadata
** metadata entries for the catalogued resources in `data/democat/`
* the vocabularies within the IDN's Register of vocabularies
** within `data/vocabularies/`
* background ontologies used to provide labelling for Prez' data
** within `data/_background/`
* IDN Prez system metadata
** within `data/system/`
** defines things like the multiple IDN catalogues, system labels etc.

Also:

* `data/unpublished/` contains data either previously published and removed but not deleted as it may be used again

Stored elsewhere are:

* Agents Database content
** some test data is stored here in but the Agents DB is building/storing its own data within it
** see the https://github.com/idn-au/agentsdb-data[AgentsDB data] repository
* Indigenous spatial reference data
** some of these datasets are large so their raw content isn't directly available
** see the repo <https://github.com/idn-au/spatial-data> for a listing of the datasets and instructions on how they are produced

== (Meta)Data Models
The metadata of items in the Demonstration Catalogue and all other catalogues based on IDN work - the UoM IDCat and the ANU's FNP's future catalogue - use the https://w3id.org/idn/def/cp[_IDN Catalogue Profile_] which is a data cataloguing standard based on https://www.w3.org/TR/vocab-dcat/[DCAT].

Agents data in the Agents Database are formulated according to the https://w3id.org/idn/def/agp[_Agents Governance Profile_].


== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.

== Contact

For technical enquiries:

**Jamie Feiss** +
*Data Infrastructure Developer* +
Indigenous Data Network +
University of Melbourne +
jamie.feiss@unimelb.edu.au

For policy:

**Levi Murray** +
*Strategic Data Manager* +
Indigenous Data Network +
University of Melbourne +
levi.murray@unimelb.edu.au

_Owner Organisation_ +
*Indigenous Data Network* +
https://idnau.org
