= IDN Catalogue Data

This repository contains the data of the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)]'s demonstration catalogue and Agents Database.

== IDN Catalogues and Databases
The IDN is producing three things:

. a **Demonstration Catalogue** of Australian datasets
.. with varying levels of indigenous relevance to demonstrate several aspects of indigenous data governance, sovereignty and how to even rate the "indigenous-ness" of data in the first place.
. an **Agents Database**
.. containing information about Agents - People and Organisations - that have some relation to indigenous data
.. this repository does contain the source data of this Database
.. see the folder _data/agents/_
. a **Catalogue of Last Resort** for indigenous data
.. this data is not linked to that catalogue

== Metadata and Data
This repository only contains the metadata files of resources listed in the Demonstration Catalogue, not the resources' data or the catalogue's system code.

It does contain the source _data_ of the items in the Agents Database currently, but this may change as the data grows.

== (Meta)Data Models
The metadata of items in both the Demonstration Catalogue and the Catalogue of Last Resort are formulated according to the https://w3id.org/idn/def/cp[_IDN Catalogue Profile_] which is a data cataloguing standard based on https://www.w3.org/TR/vocab-dcat/[DCAT].

Agents data in the Agents Database are formulated according to the https://w3id.org/idn/def/agp[_Agents Governance Profile_].

== Content
The assets in this repository are stored like this:

* `data/` folder
** contains all the metadata records for the Demonstration Catalogue
** `_background/` folder within `data/`
** contains further the ontologies used by the data, mainly for nice property labels
** `resources/` - the IDN's demo catalogue Resources (metadata records)
** `vocabularies/` - all IDN vocabularies
** `_system_catalogue.ttl` - the metadata for the IDN system as a whole

NOTE: Spatial data loaded into the IDN Knowledge Graph is not stored in this repository but in <https://github.com/idn-au/spatial-data-etl>

For the Agents Database:

* `agents/` - the Agents database


== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.


== Contacts

Initial technical development of this work is being undertaken by the following, for the Indigenous Data Network:

**Sandra Silcot** +
*Data Custodian* +
University of Melbourne +
Indigenous Data Network +

**Nicholas J. Car** +
*Data Architect* +
https://kurrawong.net[Kurrawong AI] +
nick@kurrawong.net
