# name: Validate data on PR

# on:
#   workflow_call:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   validate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repo
#         uses: actions/checkout@v3
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
#           cache: poetry
#       - name: Install Poetry
#         run: |
#           export POETRY_HOME=/opt/poetry
#           python3 -m venv $POETRY_HOME
#           $POETRY_HOME/bin/pip install poetry==1.2.0
#           $POETRY_HOME/bin/poetry --version
#       - name: Install dependencies
#         run: poetry install --without dev
#       # if files changed
#       - name: Validate catalogs
#         run: python3 validate.py -- ...
#       # if files changed
#       - name: Validate vocabs
#         run: python3 validate.py -- ...

