name: Validate data on PR

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      # Detects files changed in specific directories
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            data:
              - 'data/catalogues/**'
              - 'data/system/**'
              - 'data/vocabularies/**'
            catalogs:
              - 'data/catalogues/**'
              - 'data/system/**'
            vocabs:
              - 'data/vocabularies/**'
      # only setup for validation if any data has changed
      - name: Setup Python
        if: steps.changes.outputs.data == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
      - name: Install Poetry
        if: steps.changes.outputs.data == 'true'
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.2.0
          $POETRY_HOME/bin/poetry --version
      - name: Install dependencies
        if: steps.changes.outputs.data == 'true'
        run: poetry install --without dev
      # validate catalogue data if changed
      - name: Validate catalogs
        if: steps.changes.outputs.catalogs == 'true'
        run: python3 validate.py --catalogs
      # validate vocabulary data if changed
      - name: Validate vocabs
        if: steps.changes.outputs.vocabs == 'true'
        run: python3 validate.py --vocabs

