name: Upload data to triplestore

on:
  workflow_call:
  push:
    branches:
      - "main"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      # Detects files changed in specific directories
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            data:
              - 'data/_background/**'
              - 'data/catalogues/**'
              - 'data/system/**'
              - 'data/vocabularies/**'
            background:
              - 'data/_background/**'
            catalogs:
              - 'data/catalogues/**'
              - 'data/system/**'
            vocabs:
              - 'data/vocabularies/**'
      # only setup for upload if any data has changed
      - name: Setup Python
        if: steps.changes.outputs.data == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          # cache: poetry
      - name: Install Poetry
        if: steps.changes.outputs.data == 'true'
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.2.0
          $POETRY_HOME/bin/poetry --version
      - name: Install dependencies
        if: steps.changes.outputs.data == 'true'
        run: poetry install --without dev
      # upload background data if changed
      - name: Upload background
        if: steps.changes.outputs.background == 'true'
        run: python3 upload.py --background
        env:
          TRIPLESTORE_URL: ${{ secrets.TRIPLESTORE_URL }}
          TRIPLESTORE_USERNAME: ${{ secrets.TRIPLESTORE_USERNAME }}
          TRIPLESTORE_PASSWORD: ${{ secrets.TRIPLESTORE_PASSWORD }}
      # upload catalogue data if changed
      - name: Upload catalogs
        if: steps.changes.outputs.catalogs == 'true'
        run: python3 upload.py --catalogs
        env:
          TRIPLESTORE_URL: ${{ secrets.TRIPLESTORE_URL }}
          TRIPLESTORE_USERNAME: ${{ secrets.TRIPLESTORE_USERNAME }}
          TRIPLESTORE_PASSWORD: ${{ secrets.TRIPLESTORE_PASSWORD }}
      # upload vocabulary data if changed
      - name: Upload vocabs
        if: steps.changes.outputs.vocabs == 'true'
        run: python3 upload.py --vocabs
        env:
          TRIPLESTORE_URL: ${{ secrets.TRIPLESTORE_URL }}
          TRIPLESTORE_USERNAME: ${{ secrets.TRIPLESTORE_USERNAME }}
          TRIPLESTORE_PASSWORD: ${{ secrets.TRIPLESTORE_PASSWORD }}
